<div id="content" class="constrained content-password">
	<div class="section cleared">
		<form id="password" class="boxed" name="form-password" action="<?php echo(htmlentities($strSubmitUrl)); ?>" method="post">
			<fieldset>
				<?php 
					print Form::getHidden('action', $strActionType); 
					print Form::getHidden($strTokenField, Token::initToken());
				?>
			
				<div id="fields">
					<h1>Have you forgotten your password?</h1>
					<div class="blurb">
						Just enter your email address below and we'll email you instructions to help you reset it.
					</div>
					
					<div class="input-block labeled first">
						<label for="email" class="js-hide">Email address</label>
						<div>
							<?php echo(Form::getTextbox('email', null, array(
								'id' 	=> 'email',
								'class'	=> 'input-textbox'
							))); ?>
						</div>
					</div>
				</div>
				
				<div class="button">
					<?php echo(Form::getSubmit('submit', 'Send reset instructions')); ?>
				</div>
			</fieldset>
		</form>
			
		<div class="arrow right">
			<a href="<?php echo($strBaseUrl); ?>/account/login/">Remembered it? <strong>Sign in!</strong></a>
		</div>
	</div>
</div>