<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?php echo($strPageTitle); ?></title>
		
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=1024" />
		
		<script type="text/javascript">
			document.write('<style type="text/css">.js-hide { display: none; }</style>');
		</script>
		
		<?php
			$objController = AppRegistry::get('Controller');
			
			AppLoader::includeUtility('ConcatHelper');
			$objConcatHelper = new ConcatHelper();
			
			print $objConcatHelper->css(array(
				"{$strCssUrl}/css/common/global.css",
				"{$strCssUrl}/css/themes/{$strTheme}/common/global.css",
				"{$strCssUrl}/css/themes/{$strTheme}/common/fonts.css"
			));
			
			if (!empty($arrStylesheets)) {
				print $objConcatHelper->css($arrStylesheets);
			}
		?>
		
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/common/print.css" media="print" />
		
		<!--[if !IE]>-->
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/common/iphone.css" media="only screen and (max-device-width: 1024px)" />
		<!--<![endif]-->
		
		<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/common/ie.css" media="screen" />
		<![endif]-->
		
		<!--[if lte IE 7]>
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/common/ie7.css" media="screen" />
		<![endif]-->
		
		<!--[if lte IE 6]>
		<meta http-equiv="refresh" content="0; url=/ie6.html" />
		<script type="text/javascript">window.top.location = '/ie6.html';</script>
		<![endif]-->
	</head>
	
	<body<?php if (isset($strBodyClass)) print ' class="' . $strBodyClass . '"'; ?>>
		<div id="shell">
		