<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?php echo($strSiteTitle); ?> is coming soon!</title>
		
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/common/global.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/beta.css" media="screen" />
		
		<!--[if lte IE 7]>
		<link rel="stylesheet" type="text/css" href="<?php echo($strCssUrl); ?>/css/themes/<?php echo($strTheme); ?>/common/ie7.css" media="screen" />
		<![endif]-->
	</head>
	
	<body>
		<div id="form" class="js-hide">
			<div id="blurb">
				<span>Hello. We are in beta. A promo code is required to sign up.</span>
			</div>
			
			<?php if (!empty($arrErrors)) { ?>
			<ul id="error">
				<?php 
					foreach ($arrErrors as $strError) {
						printf('<li><span class="text">%s.</span></li>', $strError);	
					}
				?>
			</ul>
			<?php } ?>
			
			<form id="form-signup" action="<?php echo(htmlentities($strSubmitUrl)); ?>" method="post"<?php if (empty($blnSignupForm)) print ' class="hide"'; ?>>
				<fieldset>
					<?php 
						print Form::getHidden('action', $strActionType); 
						print Form::getHidden($strTokenField, Token::initToken());
					?>
					
					<div class="input-block">
						<label for="signup_promo">promo code</label>
						<div>
							<?php echo(Form::getTextbox('promo', !empty($_REQUEST['promo']) ? $_REQUEST['promo'] : null, array(
								'id' 		=> 'signup_promo',
								'maxlength'	=> 32,
								'class'		=> 'input-textbox'
							))); ?>
						</div>
					</div>
					
					<div class="input-block">
						<label for="signup_username">username</label>
						<div>
							<?php echo(Form::getTextbox('username', !empty($_POST['username']) ? $_POST['username'] : null, array(
								'id' 		=> 'signup_username',
								'maxlength'	=> 15,
								'class'		=> 'input-textbox'
							))); ?>
						</div>
					</div>
					
					<div class="input-block">
						<label for="signup_email">email</label>
						<div>
							<?php echo(Form::getTextbox('email', !empty($_POST['email']) ? $_POST['email'] : null, array(
								'id' 		=> 'signup_email',
								'maxlength'	=> 80,
								'class'		=> 'input-textbox'
							))); ?>
						</div>
					</div>
					
					<div class="input-block break">
						<label for="signup_password">password</label>
						<div>
							<?php echo(Form::getPasswordBox('password', null, array(
								'id' 		=> 'signup_password',
								'maxlength'	=> 15,
								'class'		=> 'input-password'
							))); ?>
						</div>
					</div>
					
					<div class="input-block">
						<label for="signup_password_again">and again</label>
						<div>
							<?php echo(Form::getPasswordBox('password_again', null, array(
								'id' 		=> 'signup_password_again',
								'maxlength'	=> 15,
								'class'		=> 'input-password'
							))); ?>
						</div>
					</div>
					
					<div class="buttons">
						<?php echo(Form::getSubmit('submit', 'Sign up for ' . $strSiteTitle)); ?>
					</div>
				</fieldset>
			</form>
			
			<form id="form-login" action="" method="post">
				<fieldset>
					<?php 
						print Form::getHidden($strLoginFlag, 1);
						print Form::getHidden($strTokenField, Token::initToken());
					?>
					
					<div class="input-block">
						<label for="login_username">username</label>
						<div>
							<?php echo(Form::getTextbox($strUsernameField, null, array(
								'id' 		=> 'login_username',
								'maxlength'	=> 15,
								'class'		=> 'input-textbox'
							))); ?>
						</div>
					</div>
					
					<div class="input-block break">
						<label for="login_password">password</label>
						<div>
							<?php echo(Form::getPasswordBox($strPasswordField, null, array(
								'id' 		=> 'login_password',
								'maxlength'	=> 15,
								'class'		=> 'input-password'
							))); ?>
						</div>
					</div>
					
					<div class="buttons">
						<?php echo(Form::getSubmit('submit', 'Log in to ' . $strSiteTitle)); ?>
					</div>
				</fieldset>
			</form>
		</div>
		
		<script type="text/javascript" src="<?php echo($strJsUrl); ?>/lib/jquery/js/jquery-1.5.1.min.js"></script>
		<script type="text/javascript" src="<?php echo($strJsUrl); ?>/js/themes/default/beta.js"></script>
	</body>
</html>