<div id="header">
	<div id="header-bar"></div>
	<div id="header-content" class="constrained">
		<a id="header-text" class="sprite" href="<?php echo($strBaseUrl); ?>/"><strong><?php echo($strSiteTitle); ?></strong></a>
		<a id="header-logo" class="sprite" href="<?php echo($strBaseUrl); ?>/"><span>Home</span></a>
		
		<div id="header-nav" class="notice">
			The navigation will be disabled until the installation has been completed
		</div>
	</div>
</div>
<div id="header-dots"></div>
<div id="header-shift"></div>