<div id="header">
	<div id="header-bar"></div>
	<div id="header-content" class="constrained">
		<a id="header-text" href="<?php echo($strBaseUrl); ?>/" class="chunkfive"><?php echo($strSiteTitle); ?></a>
		<a id="header-logo" class="sprite" href="<?php echo($strBaseUrl); ?>/"><strong>Home</strong></a>
		
		<div id="header-nav" class="notice">
			The navigation will be disabled until the installation has been completed
		</div>
	</div>
</div>
<div id="header-dots"></div>
<div id="header-shift"></div>