<div id="content" class="constrained">
	<p><strong>Template:</strong> <?php echo($strTemplatePath); ?></p>
	<p><strong>Controller:</strong> <?php echo($strControllerPath); ?></p>
	<p><strong>Method:</strong> <?php echo($strController); ?>::<?php echo($strDisplayMethod); ?>()</p>

	<div style="width: 150px; margin-top: 30px;">
		<a href="<?php echo($strBaseUrl); ?>/demo/" class="button">Launch Demo</a>
	</div>
</div>