<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?php echo($strPageTitle); ?></title>
		
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=1024" />
		
		<?php
			AppLoader::includeUtility('ConcatHelper');
			$objConcatHelper = new ConcatHelper();
			
			print $objConcatHelper->css(array(
				"{$strCssUrl}/css/common/global.css",
				"{$strCssUrl}/css/themes/{$strTheme}/common/global.css"
			));
			
			if (!empty($arrStylesheets)) {
				print $objConcatHelper->css($arrStylesheets);
			}
		?>
	</head>
	
	<body<?php if (isset($strBodyClass)) print ' class="' . $strBodyClass . '"'; ?>>
		